# Generated by Django 5.1.3 on 2024-11-23 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, max_length=55, null=True)),
                ('barangay', models.CharField(blank=True, max_length=55, null=True)),
                ('city', models.CharField(blank=True, max_length=55, null=True)),
                ('province', models.CharField(blank=True, max_length=55, null=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('middle_name', models.CharField(blank=True, max_length=55, null=True)),
                ('suffix', models.CharField(blank=True, max_length=55, null=True)),
                ('email', models.CharField(blank=True, max_length=55, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=55, null=True)),
                ('password', models.CharField(blank=True, max_length=55, null=True)),
            ],
            options={
                'db_table': 'instructor',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=55, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(blank=True, max_length=55, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'program',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('REGISTRAR', 'Registrar'), ('DEPARTMENT', 'Department'), ('STUDENT', 'Student')], max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=55)),
                ('title', models.CharField(blank=True, max_length=55, null=True)),
                ('lab_units', models.IntegerField(blank=True, null=True)),
                ('lec_units', models.IntegerField(blank=True, null=True)),
                ('total_units', models.IntegerField(blank=True, null=True)),
                ('year_level', models.IntegerField(blank=True, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('school_year', models.CharField(blank=True, max_length=55, null=True)),
                ('pre_requisite', models.CharField(blank=True, max_length=55, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.program')),
            ],
            options={
                'db_table': 'course',
                'unique_together': {('code', 'program')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('middle_name', models.CharField(blank=True, max_length=55, null=True)),
                ('suffix', models.CharField(blank=True, max_length=55, null=True)),
                ('year_level', models.IntegerField(blank=True, null=True)),
                ('section', models.IntegerField(blank=True, null=True)),
                ('old_or_new', models.CharField(blank=True, choices=[('OLD', 'Old'), ('NEW', 'New')], max_length=3, null=True)),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular'), ('TRANFEREE', 'Tranferee'), ('RETURNEE', 'Returnee'), ('NEW STUDENT', 'New')], max_length=55)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('PREFER NOT TO SAY', 'Prefer Not To Say')], max_length=17, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=55, null=True)),
                ('email', models.CharField(blank=True, max_length=55, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.address')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.program')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=55, null=True)),
                ('last_name', models.CharField(blank=True, max_length=55, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=55, null=True)),
                ('suffix', models.CharField(blank=True, max_length=55, null=True)),
                ('email', models.CharField(blank=True, max_length=55, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=55, null=True)),
                ('username', models.CharField(db_comment='Student will use their student number for username. Registrar, Admin and Department has different format for username', max_length=55, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.role')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('LAB', 'Lab'), ('LEC', 'Lec')], max_length=3, null=True)),
                ('day', models.CharField(blank=True, choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=55, null=True)),
                ('room', models.CharField(blank=True, max_length=55, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instructor')),
            ],
            options={
                'db_table': 'schedule',
                'unique_together': {('day', 'from_time', 'to_time')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('grade', models.DecimalField(blank=True, db_comment='1.00 to 5.00 scale', decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.CharField(blank=True, choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('INCOMPLETE', 'Incomplete'), ('UNCONDITIONAL_FAILURE', 'Unconditional Failure'), ('NOT_GRADED_YET', 'Not Graded Yet')], max_length=21, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instructor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'db_table': 'grade',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('WAITLISTED', 'Waitlisted')], max_length=10)),
                ('school_year', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
                ('checked_by', models.ForeignKey(blank=True, db_column='checked_by', db_comment='Role must be Department', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('released_by', models.ForeignKey(blank=True, db_column='released_by', db_comment='Role must be Registrar', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_released_by_set', to='api.user')),
            ],
            options={
                'db_table': 'enrollment',
                'unique_together': {('course', 'student')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('permission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.role')),
            ],
            options={
                'db_table': 'role_permission',
                'unique_together': {('permission', 'role')},
            },
        ),
    ]
