# Generated by Django 5.1.3 on 2024-11-29 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=55, null=True)),
                ('barangay', models.CharField(blank=True, max_length=55, null=True)),
                ('city', models.CharField(max_length=55)),
                ('province', models.CharField(max_length=55)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('middle_name', models.CharField(blank=True, max_length=55, null=True)),
                ('suffix', models.CharField(blank=True, max_length=55, null=True)),
                ('email', models.CharField(blank=True, max_length=55, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=55, null=True)),
            ],
            options={
                'db_table': 'instructor',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=55)),
                ('title', models.CharField(max_length=55)),
                ('lab_units', models.IntegerField(blank=True, null=True)),
                ('lec_units', models.IntegerField(blank=True, null=True)),
                ('contact_hr_lab', models.IntegerField(blank=True, null=True)),
                ('contact_hr_lec', models.IntegerField(blank=True, null=True)),
                ('year_level', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('program', models.CharField(choices=[('NO_PROGRAM_YET', 'No Program Yet'), ('BSIT', 'Bsit'), ('BSCS', 'Bscs')], default='NO_PROGRAM_YET', max_length=14)),
            ],
            options={
                'db_table': 'course',
                'unique_together': {('code', 'program')},
            },
        ),
        migrations.CreateModel(
            name='PreRequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_course_set', to='api.course')),
                ('pre_requisite', models.ForeignKey(db_column='pre_requisite', on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
            options={
                'db_table': 'pre_requisite',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=55, null=True, unique=True)),
                ('middle_name', models.CharField(blank=True, max_length=55, null=True)),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('suffix', models.CharField(blank=True, max_length=55, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('PREFER NOT TO SAY', 'Prefer Not To Say')], max_length=17)),
                ('contact_number', models.CharField(blank=True, max_length=55, null=True)),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular'), ('TRANFEREE', 'Tranferee'), ('RETURNEE', 'Returnee'), ('NEW STUDENT', 'New')], max_length=11)),
                ('section', models.IntegerField()),
                ('year_level', models.IntegerField()),
                ('academic_year', models.CharField(blank=True, max_length=55, null=True)),
                ('category', models.CharField(choices=[('OLD', 'Old'), ('NEW', 'New')], max_length=3)),
                ('program', models.CharField(choices=[('NO_PROGRAM_YET', 'No Program Yet'), ('BSIT', 'Bsit'), ('BSCS', 'Bscs')], default='NO_PROGRAM_YET', max_length=14)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=55)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'db_table': 'billing',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('year_level', models.IntegerField()),
                ('section', models.IntegerField()),
                ('category', models.CharField(blank=True, choices=[('LAB', 'Lab'), ('LEC', 'Lec')], max_length=3, null=True)),
                ('day', models.CharField(blank=True, choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=9, null=True)),
                ('room', models.CharField(blank=True, max_length=55, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instructor')),
            ],
            options={
                'db_table': 'schedule',
                'unique_together': {('course', 'category', 'day', 'from_time', 'to_time')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, db_comment='1.00 to 5.00 or S scale', max_length=4, null=True)),
                ('remarks', models.CharField(blank=True, choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('INCOMPLETE', 'Incomplete'), ('UNCONDITIONAL_FAILURE', 'Unconditional Failure'), ('NOT_GRADED_YET', 'Not Graded Yet')], max_length=21, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instructor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'db_table': 'grade',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('WAITLISTED', 'Waitlisted')], max_length=10)),
                ('school_year', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'db_table': 'enrollment',
                'unique_together': {('course', 'student')},
            },
        ),
    ]
