# Generated by Django 5.1.3 on 2024-11-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=55)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'billing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreRequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'pre_requisite',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
