# Generated by Django 5.1.3 on 2024-11-20 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=55)),
                ('barangay', models.CharField(max_length=55)),
                ('city', models.CharField(max_length=55)),
                ('province', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('middle_name', models.CharField(blank=True, max_length=55, null=True)),
                ('suffix', models.CharField(blank=True, max_length=55, null=True)),
                ('email', models.EmailField(max_length=55)),
                ('contact_number', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(max_length=55)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('REGISTRAR', 'Registrar'), ('DEPARTMENT', 'Department'), ('STUDENT', 'Student')], max_length=15)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=55)),
                ('title', models.CharField(max_length=55)),
                ('lab_units', models.PositiveIntegerField()),
                ('lec_units', models.PositiveIntegerField()),
                ('total_units', models.PositiveIntegerField()),
                ('year_level', models.PositiveIntegerField()),
                ('semester', models.PositiveIntegerField()),
                ('school_year', models.CharField(max_length=55)),
                ('pre_requisite', models.CharField(blank=True, max_length=55, null=True)),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.program')),
            ],
            options={
                'unique_together': {('code', 'program_id')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('middle_name', models.CharField(blank=True, max_length=55, null=True)),
                ('suffix', models.CharField(blank=True, max_length=55, null=True)),
                ('year_level', models.PositiveIntegerField()),
                ('section', models.PositiveIntegerField()),
                ('old_or_new', models.CharField(choices=[('OLD', 'Old'), ('NEW', 'New')], default='OLD', max_length=55)),
                ('status', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular'), ('TRANFEREE', 'Tranferee'), ('RETURNEE', 'Returnee'), ('NEW STUDENT', 'New')], default='REGULAR', max_length=55)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('PREFER NOT TO SAY', 'Prefer Not To Say')], max_length=55, null=True)),
                ('contact_number', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=55)),
                ('address_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.address')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.program')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('middle_name', models.CharField(blank=True, max_length=55, null=True)),
                ('suffix', models.CharField(blank=True, max_length=55, null=True)),
                ('email', models.EmailField(max_length=55)),
                ('contact_number', models.CharField(max_length=55)),
                ('username', models.CharField(max_length=55, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.role')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.permission')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.role')),
            ],
            options={
                'unique_together': {('permission_id', 'role_id')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('category', models.CharField(choices=[('LAB', 'Lab'), ('LEC', 'Lec')], max_length=55)),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=55)),
                ('room', models.CharField(max_length=55)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instructor')),
            ],
            options={
                'unique_together': {('day', 'from_time', 'to_time')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('remarks', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('INCOMPLETE', 'Incomplete'), ('UNCONDITIONAL_FAILURE', 'Unconditional Failure'), ('NOT_GRADED_YET', 'Not Graded Yet')], default='NOT_GRADED_YET', max_length=30)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instructor')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
            options={
                'unique_together': {('student_id', 'course_code')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('WAITLISTED', 'Waitlisted')], max_length=10)),
                ('school_year', models.DateField()),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_enrollments', to='app.user')),
                ('released_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='released_enrollments', to='app.user')),
            ],
            options={
                'unique_together': {('course_code', 'student_id')},
            },
        ),
    ]
