# Generated by Django 5.1.3 on 2024-11-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=55)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
    ]
